### ISSUE TITLE
Error related to backend state file

### ISSUE THREAD

**Issue by harish417** [guitmz/3-tier-app-aws-terraform#1]
When running terraform init with the backend-config argument I am getting an error

Error configuring the backend "s3": No valid credential sources found for AWS Provider.
Please see https://terraform.io/docs/providers/aws/index.html for more information on
providing credentials for the AWS Provider

Please update the configuration in your Terraform files to fix this error
then run this command again.

So how do I resolve this error.

Thanks and regards,
Harish

**Comment by guitmz** [comment]
@harish417 you need to provide terraform a way to access AWS (to create/interact with s3 bucket defined in `terraform.remote` file).

https://github.com/guitmz/3-tier-app-aws-terraform#requirements

Using environment variables with your AWS credentials should be enough. Please reopen if you have any other issues.

Thanks!
